JSPrismarine/JSPrismarine

README.md, start.cmd, start.sh
It's not totaly equivalent to the windows script but get the job done.
=> Added start script for Linux/MacOS

README.md
This should reduce further confusion about joining the server via localhost
=> Update FAQ 

README.md
I decided to remove the languages/transpilers links because people know what they want and there is no guarantee these language will work for making plugin and removed the thing for joining the server on other platform (xbox one, ps4 switch) because this is an obselete way to do that and most of consoles don't care about the software itself and will never read the README.
=> Removed some useless change

src/command/command-manager.js, src/command/command.js, src/command/vanilla/gamemode-command.js, src/events/event-identifiers.js, src/events/event-manager.js, src/player.js, src/prismarine.js, src/utils/buffer-to-console-string.js
Object Decunstructing on command type
AnyEvent event type
bufferToConsoleString for buffer logging with custom logger
Command now Extends the CommandData
server.listen() port support server.listen([_port=19132])
=> Some Good Changes

src/command/command-manager.js
Please update to fork because its crashes the build.
=> removed help command from command-manager sory for my mistake

bootstrap.js, package.json, src/command/vanilla/stop-command.js, src/events/base-event.js, src/plugin/plugin-manager.js, src/plugin/types/plugin-manifest-type.js, src/plugin/types/plugin-type.js, src/prismarine.js, src/utils/config/plugin-config.js, src/world/world-manager.js
```
plugins
| examplePlugin
| src
| main.js
| manifest.json
```
`manifest.json`:
```json
{
"name": "Example Plugin",
"description": "Example Description",
"version": "0.0.1",
"indexFile": "./src/main.js",
"apiVersion": "0.0.1"
}
```
`./src/main.js`:
```js
const Prismarine = require("../../src/prismarine")
/**
* @param {Prismarine} server 
*/
module.exports = (server)=>{
server.logger.debug("Hello World!")
}
```
=> Better Plugin Support

.gitignore, package-lock.json
As per the NPM & yarn documentation the package lockfile is intended to be committed into repositories to prevent inconstancies between different environments.
See https://docs.npmjs.com/configuring-npm/package-lock-json.html & https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/ for more information.
=> Adhere to NPM docs regarding package-lock.

README.md, package.json
This also adds the ```npm run dev``` command for development purposes.
=> npm start by default uses NODE_ENV production.

src/command/vanilla/me-command.js, src/command/vanilla/say-command.js, src/network/handler/text-handler.js
This fixes the chat log level.
=> Fix chat log level.

src/command/vanilla/list-command.js, src/command/vanilla/me-command.js
Fix server crashes from running list and me commands.
=> Fix list & me commands.

src/command/vanilla/gamemode-command.js, src/network/handler/creative-content-handler.js, src/network/packet-binary-stream.js, src/network/packet/creative-content-packet.js, src/network/type/creative-content-entry.js, src/player.js
This is the first required step to get the creative inventory working.
References:
* https://github.com/pmmp/PocketMine-MP/blob/e990c5a0a57a651c5d6a0796d0692a1d6aae868d/src/pocketmine/network/mcpe/protocol/CreativeContentPacket.php#L57
* https://github.com/pmmp/PocketMine-MP/blob/e990c5a0a57a651c5d6a0796d0692a1d6aae868d/src/pocketmine/inventory/PlayerInventory.php#L195
* https://github.com/pmmp/PocketMine-MP/blob/9365525efa45693d6ee025747938bcd0642ef3fc/src/pocketmine/Player.php#L1432
=> CreativeContentPacket

.github/workflows/test.yml, jest.config.js, package-lock.json, package.json, src/command/command-manager.js, src/command/command.test.js, src/command/vanilla/gamemode-command.js, src/command/vanilla/gamemode-command.test.js, src/command/vanilla/list-command.test.js, src/math/vector3.test.js, src/network/packet-registry.js
This should be extended to in the future test network packets etc.
=> Initial jest testing & GitHub workflows support.

.eslintrc, .github/workflows/test.yml, package-lock.json, package.json, src/command/command.js, src/command/jsprismarine/plugins-command.js, src/network/type/set-title-type.js, src/plugin/plugin-api.js, src/plugin/plugin-manager.js, src/prismarine.js, src/utils/logger.js, src/utils/skin/skin-image.js, src/world/chunk-radius-checker.js, src/world/coordinate-utils.js, src/world/experimental/experimental.js, src/world/leveldb/leveldb.js, src/world/provider.js, src/world/world-manager.js
This will automatically run on commit.
=> Add eslint

package-lock.json, package.json
Husky is completely unnecessary to have as a dependency in production. This resolves that issue.
=> Husky should be a devDependency.

bootstrap.js, package-lock.json, package.json, src/command/command-manager.js, src/inventory/item/item-manager.js, src/network/handler/resource-pack-response-handler.js, src/utils/logger.js, src/world/generator-manager.js, src/world/generators/flat.js, src/world/generators/overworld.js, src/world/leveldb/leveldb.js, src/world/world-manager.js, src/world/world.js
Still under heavy development, will document tomorrow.
=> Initial generator implementation

src/network/handler/player-action-handler.js, src/network/packet/update-block.js
Added new packet UpdateBlock and use to update block break. To fix #18
=> Add UpdateBlock and enhance PlayerActionHandler

src/Prismarine.ts, src/events/EventEmitterishMixin.ts, src/events/EventManager.ts, src/plugin/api/versions/1.0/EventManager.ts, src/plugin/api/versions/1.0/PluginApi.ts
[See here](https://gist.github.com/garronej/84dddc6dad77d9fd0ce5608148bc59c4#gistcomment-3506538)
=> Enable plugin makers to post custom events

src/Prismarine.ts
Nothing important, just had 10min to kill.
=> Random refactor to promote functional programing

src/player/PlayerConnection.ts
=> Fix: Display items correctly in creative inventory

src/config/ConfigBuilder.ts, src/network/packet/LoginPacket.ts, src/network/packet/StartGamePacket.ts, src/network/raknet/Connection.ts, src/network/raknet/Listener.ts, src/query/QueryManager.ts, src/world/World.ts, src/world/WorldManager.ts, src/world/leveldb/Leveldb.ts
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/jsprismarine/jsprismarine/issues).
=> Apply fixes from CodeFactor

package-lock.json, package.json, src/Console.ts, src/command/CommandArguments.ts, src/command/vanilla/GamemodeCommand.ts, src/command/vanilla/TpCommand.ts, src/entity/entity.ts, src/entity/metadata.ts, src/entity/passive/Sheep.ts, src/network/packet/AvailableCommandsPacket.ts, src/network/type/CommandParameter.ts, src/player/Player.ts, src/player/PlayerConnection.ts, src/utils/ParseEntityArgument.test.ts, src/utils/ParseEntityArgument.ts, src/world/World.ts
This will to some extent handle `@a`, `@e`, `@p`, `@r` and `@s` target selectors with a parameter system implemented (however that currently only supports the `type` parameter).
=> Target argument parsing.

src/block/blocks/BlackBed.ts, src/block/blocks/BlueBed.ts, src/block/blocks/BrownBed.ts, src/block/blocks/CyanBed.ts, src/block/blocks/GrayBed.ts, src/block/blocks/GreenBed.ts, src/block/blocks/LightBlueBed.ts, src/block/blocks/LightGrayBed.ts, src/block/blocks/LimeBed.ts, src/block/blocks/MagentaBed.ts, src/block/blocks/OrangeBed.ts, src/block/blocks/PinkBed.ts, src/block/blocks/PurpleBed.ts, src/block/blocks/RedBed.ts, src/block/blocks/WhiteBed.ts, src/block/blocks/YellowBed.ts
pls check my spellings i am bad at spelling :)
=> Added colored beds

src/network/PacketRegistry.ts, src/network/packet/RemoveObjectivePacket.ts, src/network/packet/SetDisplayObjectivePacket.ts, src/network/packet/SetScorePacket.ts, src/network/packet/SetScoreboardIdentityPacket.ts
Adding the packets RemoveObjectivePacket.ts, SetDisplayObjectivePacket.ts, SetScorePacket.ts, and SetScoreboardIdentityPacket.ts.
Modified PacketRegistry.ts to register the packets.
=> Adding scoreboard packets

src/command/CommandManager.ts, src/events/EventManager.ts, src/events/command/CommandRegisterEvents.ts
Adding a Command Register Event.
=> Add Command Register Event

src/command/CommandManager.ts, src/events/EventManager.ts, src/events/items/ItemRegisterEvent.ts, src/item/ItemManager.ts
Adding An Item Register Event.
Fixed Item and Command debug Registered count.
=> Add Register Event and Fix Debug registered count

packages/prismarine/src/command/CommandArguments.ts, packages/prismarine/src/command/vanilla/ExecuteCommand.ts, packages/prismarine/src/network/PacketRegistry.ts
Added the execute command and a new command argument.
=> Add execute command

package-lock.json, packages/prismarine/src/Managers.ts, packages/prismarine/src/Server.ts
* Add missing export in Managers, add a fixed tick time instead of math...
* Still missing constant name for tick time
=> chore(fix): export SessionManager and add fixed time to tick

package-lock.json, package.json, packages/prismarine/src/network/handler/MovePlayerHandler.ts
* due to dependecy issues, temporary remove interpolation
=> fix(interpolation): temporary remove interpolation

README.md
ignore this, trying to get rid of a leftover from a previous account.
This fixes #199.
=> chore(readme): Add dev remark.

.github/workflows/release.yml
We should switch to changeset.
=> CI: Maybe fix `release` workflow.

packages/prismarine/src/Player.ts, packages/prismarine/src/Server.ts, packages/prismarine/src/network/ClientConnection.ts
Moved some disconnection logic in the right place.
=> Prismarine: Improve player disconnection.

packages/brigadier/src/builder/RequiredArgumentBuilder.ts
this makes the whole code show less error, it's great
=> [brigadier] making the argument function allow custom command source

.changeset/tall-boats-shake.md, packages/brigadier/src/StringReader.test.ts, packages/brigadier/src/StringReader.ts
=> brigadier: Support both single and double quotes.
